In [8]:
import numpy as np

# 1. Ways to create a list and numpy array

lst = [1,2,3,4,5]
print(lst)
print(type(lst))

array = np.array(lst)
print(array)
print(type(array))
print("")

# 2. In list if we add two list then its merging the two list but in np array if we add two list it exactly add two array, element by element.
print(lst+lst)
print(array+array)
print("")

# 3. If we using repetition a list returns printing the list n times but in np array its multiply each element in an array that's the diff.
print(lst*3)
print(array*3)
print("")

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]

