In [1]:
import os

print(os.getcwd())

C:\Users\My_Sowriyam\Code io - NumPy


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
np.save("data.npy",arr)

In [4]:
read = np.load("data.npy")
print(read)

[1 2 3 4 5]


In [5]:
brr = np.array([6,7,8,9,0])
np.savez("merged.npz",arr,brr)

In [10]:
read = np.load("merged.npz")
print(read)
print()

print(read["arr_0"])
print()

print(read["arr_1"])
print()

NpzFile 'merged.npz' with keys: arr_0, arr_1

[1 2 3 4 5]

[6 7 8 9 0]



In [13]:
# Linear Algebra

# Matrix Multiplication

a = np.array([
    [1,2],
    [4,5]
])

b = np.array([
    [4,5],
    [7,8]
])

print(np.matmul(a,b))
print()

[[18 21]
 [51 60]]



In [14]:
# Dot Matrix

a = np.array([1,2,3])
b = np.array([1,2,3])

print(np.dot(a,b))
print()

14



In [16]:
# Transpose of a Matrix
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr.T)
print()

print(np.linalg.det(arr))

[[1 4 7]
 [2 5 8]
 [3 6 9]]

0.0
