In [ ]:
import numpy as np

# 1. In Python type() returns the type of the array but here NumPy returns the actual type of the array
array = np.array([1,2,3,4,5])
print(array)
print(type(array))
print(array.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [ ]:
# 2. Defaultly it used int32 here if we did not mentioned dtype and each element stores 32 bit which is 4 bytes so totally 20 bytes

array = np.array([1,2,3,4,5])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

# 3. We can also set manually like this and here we set int16 so each element stores 16 bit which is 2 bytes so totally 10 bytes

array = np.array([1,2,3,4,5], dtype = np.int16)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

[1 2 3 4 5]
int32
20 bytes

[1 2 3 4 5]
int16
10 bytes


In [ ]:
# 4. Defaultly it used float64 here if we did not mentioned dtype and each element stores 64 bit which is 8 bytes so totally 40 bytes

array = np.array([1.5,2.6,3.3,4,5])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

# 5.  We can also set manually like this and here we set float32 so each element stores 32 bit which is 4 bytes so totally 20 bytes
array = np.array([1.5,2.6,3.3,4,5], dtype = np.float32)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

[1.5 2.6 3.3 4.  5. ]
float64
40 bytes

[1.5 2.6 3.3 4.  5. ]
float32
20 bytes


In [ ]:
# 6. Defaultly it used str_ here if we did not mentioned dtype and <U8 means take longest len word here is dheeksha

array = np.array(["vijay", "swathi", "dheeksha"])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

array = np.array(["vijay", "swathi", "dheeksha"], dtype = np.str_)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

['vijay' 'swathi' 'dheeksha']
<U8
96 bytes

['vijay' 'swathi' 'dheeksha']
<U8
96 bytes



In [ ]:
# 7. We can store multiple elements but it always take str_ dtype defaultly

array = np.array([1, 4.0, True, "Vijay"])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

array = np.array([1, 4.0, True, "Vijay"], dtype = np.str_)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

array = np.array([1, 4.0, True, "Vijay"], dtype = np.object_)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

['1' '4.0' 'True' 'Vijay']
<U32
512 bytes

['1' '4.0' 'True' 'Vijay']
<U5
80 bytes

[1 4.0 True 'Vijay']
object
32 bytes



In [ ]:
# 8. We can store boolean value also

array = np.array([True, False, True, False, True])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

array = np.array([True, False, True, False, True], dtype = np.bool_)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

[ True False  True False  True]
bool
5 bytes

[ True False  True False  True]
bool
5 bytes



In [ ]:
# 9. We can also convert a type using astype()

array = np.array([1.5,2.6,3.3,4,5])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

array = array.astype(np.str_)
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")
print("")

[1.5 2.6 3.3 4.  5. ]
float64
40 bytes

['1.5' '2.6' '3.3' '4.0' '5.0']
<U32
640 bytes

