In [15]:
import numpy as np

# 1. If only one element inside an array it should be called 0 dimensional array.
# 2. Collection of elements -> array - 2 dimension
# 3. Collectin of array -> matrix - 3 dimension ( low, column, layer)

# Example : A single paper has only length and width not a height which is 2 dimension
# Example : If thousands of paper joined then it should have some height 
#           which is called layer here - 3 dimension

arr = np.array(1)
print(arr)
print(f"{arr.ndim} Dimentional Array")

arr = np.array(
    [1,2,3]
)
print(arr)
print(f"{arr.ndim} Dimentional Array")

mat = np.array([
    [1,2,3],
    [4,5,6]
])
print(mat)
print(f"{mat.ndim} Dimentional Array")

arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [12,22,32],
        [42,52,62]
    ]
])
print(arr)
print(f"{arr.ndim} Dimentional Array")

1
0 Dimentional Array
[1 2 3]
1 Dimentional Array
[[1 2 3]
 [4 5 6]]
2 Dimentional Array
[[[ 1  2  3]
  [ 4  5  6]]

 [[12 22 32]
  [42 52 62]]]
3 Dimentional Array


In [13]:
# Indexing for 2D -> Rows, Columns
print(mat)
print(f"1st row 1st value : {mat[0][0]}")
print(f"2nd row 1st value : {mat[1][0]}")
# If we used mat[3][6] it will give an error

[[1 2 3]
 [4 5 6]]
1st row 1st value : 1
2nd row 1st value : 4


In [19]:
# Indexing for 3D -. Layers, Rows, Columns (Chain Indexing)
print(arr)
print(f"1st layer 1st row 1st column : {arr[0][0][0]}")
print(f"value 32 fetching : {arr[1][0][2]}")

# NumPy Multidimensional Indexing
print(arr[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[12 22 32]
  [42 52 62]]]
1st layer 1st row 1st column : 1
value 32 fetching : 32
62


In [20]:
# Finding the shape of an array

print(arr)
print(f"Shape of an array : {arr.shape}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[12 22 32]
  [42 52 62]]]
Shape of an array : (2, 2, 3)


In [33]:
# Reshaping the exisiting using Reshape

# Note : If we have 10 elements then we can give 2,5 not 2,6 because it lead 12 elements.
#        Parameter value should be total number elements in an array.
a = np.array([1,2,3,4,5,6,7,8,9,0])
print(a)
print()

print(f"Before {a.ndim} Dimentional Array")
print(f"Before Shape of an array : {a.shape}")
print()

a = a.reshape(2,5)

print(f"After  {a.ndim} Dimentional Array")
print(f"After  Shape of an array : {a.shape}")
print()

print(arr)
print()

print(f"Before {arr.ndim} Dimentional Array")
print(f"Before Shape of an array : {arr.shape}")
print()

arr = arr.reshape(2,6)
print(f"After  {arr.ndim} Dimentional Array")
print(f"After  Shape of an array : {arr.shape}")
print()

print(arr)
print()

[1 2 3 4 5 6 7 8 9 0]

Before 1 Dimentional Array
Before Shape of an array : (10,)

After  2 Dimentional Array
After  Shape of an array : (2, 5)

[[ 1  2  3  4  5  6]
 [12 22 32 42 52 62]]

Before 2 Dimentional Array
Before Shape of an array : (2, 6)

After  2 Dimentional Array
After  Shape of an array : (2, 6)

[[ 1  2  3  4  5  6]
 [12 22 32 42 52 62]]



In [35]:
print(arr)
print()

arr = arr.reshape(3,-1)
print(arr)
print()

arr = arr.reshape(-1,3)
print(arr)
print()

[[ 1  2  3  4  5  6]
 [12 22 32 42 52 62]]

[[ 1  2  3  4]
 [ 5  6 12 22]
 [32 42 52 62]]

[[ 1  2  3]
 [ 4  5  6]
 [12 22 32]
 [42 52 62]]

