In [5]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr)

print("1st row printing : ",arr[0]) # Zero based indexing
print("2nd row printing : ",arr[1])
print("3rd row printing : ",arr[-1]) # Negative indexing also supporting like Python

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1st row printing :  [1 2 3]
2nd row printing :  [4 5 6]
3rd row printing :  [7 8 9]


In [7]:
# Indexing

print("1st row 2nd value : ",arr[0][2])
print("2nd row 1st value : ",arr[1,0])

1st row 2nd value :  3
2nd row 1st value :  4


In [12]:
# Slicing -> [start : End : Step ]

print(arr[1:3]) # Here Start is inclusive and End is exclusive
print()

print(arr[0:3:2]) # Here Skip the rows just like that
print()

print(arr[1:]) # Here if we not mentioned end it will go upto end
print()

print(arr[::]) # Here both start and end not given then it should go from to end
print()

print(arr[::-1]) # We can also use negative indexing also - it reverse the array
print()

[[4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [17]:
# Column Slicing

print(arr)
print()

print(arr[:,0:2])
print()

print(arr[:,::2])
print()

print(arr[::-1])
print(arr[:,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]
 [7 8]]

[[1 3]
 [4 6]
 [7 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [25]:
print(arr)
print()

print("1. Top Left Sub Matrix : ")
print(arr[0:2:1,0:2:1])

print("2. Top right Sub Matrix : ")
print(arr[0:2:1,1:3:1])

print("3. Bottom Left Sub Matrix : ")
print(arr[1:3:1,0:2:1])

print("4. Bottom Right Sub Matrix : ")
print(arr[1:3:1,1:3:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. Top Left Sub Matrix : 
[[1 2]
 [4 5]]
2. Top right Sub Matrix : 
[[2 3]
 [5 6]]
3. Bottom Left Sub Matrix : 
[[4 5]
 [7 8]]
4. Bottom Right Sub Matrix : 
[[5 6]
 [8 9]]


In [29]:
# Example

arr = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [6,7,8,9],
    [1,5,7,9]
])

print(arr)
print()

print("Center part of the array : ")
print(arr[1:3:,1:3:])

[[1 2 3 4]
 [4 5 6 7]
 [6 7 8 9]
 [1 5 7 9]]

Center part of the array : 
[[5 6]
 [7 8]]
