In [1]:
import numpy as np

arr = np.array([24,5,6,2])

print(arr + 100)
print(arr - 5)
print(arr * 10)
print(arr / 5)
print(arr ** 5)

[124 105 106 102]
[19  0  1 -3]
[240  50  60  20]
[4.8 1.  1.2 0.4]
[7962624    3125    7776      32]


In [3]:
sqrt = np.sqrt(arr)
print(sqrt)
print(np.round(sqrt))
print(np.floor(sqrt))
print(np.ceil(sqrt))

[4.89897949 2.23606798 2.44948974 1.41421356]
[5. 2. 2. 1.]
[4. 2. 2. 1.]
[5. 3. 3. 2.]


In [4]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [5]:
print(np.pi)

3.141592653589793


In [9]:
age = np.array([24,45,34,8,16,18])
print(age)
print(age < 18)
print(age == 18)
print(age >= 18)

age[age<18] = 18
print(age)

age[age>30] = 50
print(age)

[24 45 34  8 16 18]
[False False False  True  True False]
[False False False False False  True]
[ True  True  True False False  True]
[24 45 34 18 18 18]
[24 50 50 18 18 18]
