In [1]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

brr = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

(3, 3)
(3, 3)
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [2]:
arr = np.array([
    [1,2,3],
])

brr = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

# Here first matrix has only one row so it replicates itself for matching the shape of second matrix which is 3 x 3

(1, 3)
(3, 3)
[[1 4 9]
 [1 4 9]
 [1 4 9]]


In [3]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

brr = np.array([
    [1,2,3],
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

# Here second matrix has only one row so it replicates itself for matching the shape of first matrix which is 3 x 3

(3, 3)
(1, 3)
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [4]:
arr = np.array([
    [1],
    [2],
    [3]
])

brr = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

# Here first matrix has only 1 column so it replicates itself to match second matrix shape

(3, 1)
(3, 3)
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [5]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

brr = np.array([
    [1],
    [2],
    [3]
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

# Here second matrix has only 1 column so it replicates itself to match first matrix shape

(3, 3)
(3, 1)
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [6]:
arr = np.array([
    [1],
    [2],
    [3]
])

brr = np.array([
    [1,2,3],
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

# Here every matrix matches their other matrix shape itself

(3, 1)
(1, 3)
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [7]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

brr = np.array([
    [1,2],
    [2,2],
    [3,2]
])

print(arr.shape)
print(brr.shape)
print(arr * brr)

# ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 
# We need correct shape for matching other matrix or exact 1 but here second matrix column is 2 so it cause error.

(3, 3)
(3, 2)


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 