In [1]:
import numpy as np

In [5]:
# Zeros function

zeros = np.zeros((2))
print(zeros)
print()

zeros = np.zeros((2,2))
print(zeros)
print()

zeros = np.zeros((2,2,3))
print(zeros)
print()

[0. 0.]

[[0. 0.]
 [0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]



In [9]:
# Ones function

# Syntax :
#        arr_name = np.ones((no_of_array_shape if one dimensional just mentioned total values))

ones = np.ones((2)) # here one dimensional with 2 values
ones = np.array(ones,dtype = np.str_)
print(ones)
print()

ones = np.ones((2,2)) # here 2 x 2 matrix
print(ones)
print()

ones = np.ones((2,2,3)) # here we created 2 layers with 2 rows and 3 columns
print(ones)
print()

['1.0' '1.0']

[[1. 1.]
 [1. 1.]]

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



In [13]:
# Full function

# Syntax :
#        arr_name = np.full((no_of_array_shape if one dimensional just mentioned total values), value_with_filled)

arr = np.full((2),2)
print(arr)
print()

arr = np.full((2,2),2)
print(arr)
print()

arr = np.full((2,2,3),100)
print(arr)
print()

[2 2]

[[2 2]
 [2 2]]

[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]



In [15]:
# Identity matrix

arr = np.eye(3)
print(arr)
print()

arr = np.eye(2)
print(arr)
print()

arr = np.eye(5)
print(arr)
print()

arr = np.eye(1)
print(arr)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0.]
 [0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1.]]



In [17]:
# Empty function

arr = np.empty(2)
print(arr)
print()

arr = np.empty((2,3))
print(arr)
print()

[1. 1.]

[[2.12199579e-312 2.12199579e-312 2.12199579e-312]
 [2.12199579e-312 2.12199579e-312 2.12199579e-312]]



In [18]:
# A range function

arr = np.arange(0,100,5)
print(arr)
print()

arr = np.arange(0,100,8)
print(arr)
print()

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

[ 0  8 16 24 32 40 48 56 64 72 80 88 96]



In [19]:
# Linspace function

# Note : Here end value should also included

arr = np.linspace(0,100,6)
print(arr)
print()

arr = np.linspace(0,100,13)
print(arr)
print()

[  0.  20.  40.  60.  80. 100.]

[  0.           8.33333333  16.66666667  25.          33.33333333
  41.66666667  50.          58.33333333  66.66666667  75.
  83.33333333  91.66666667 100.        ]



In [40]:
# Aggragate functions

arr = np.arange(0,20,3)
print(arr)
print()

print(f"Minimum value : {arr.min()}")
print(f"Maximum value : {arr.max()}")
# print(f"Average value : {arr.avg()}") # Here avg function wont work because that is python aggragate function thats why
print(f"Average value : {arr.mean()}")
print(f"Median value : {np.median(arr)}")
print(f"Sum value : {arr.sum()}")
print(f"Stadard deviation value : {arr.std()}")
print(f"Variance value : {arr.var()}")
print(f"Minimum value position : {arr.argmin()}")
print(f"Maximum value position : {arr.argmax()}")

[ 0  3  6  9 12 15 18]

Minimum value : 0
Maximum value : 18
Average value : 9.0
Median value : 9.0
Sum value : 63
Stadard deviation value : 6.0
Variance value : 36.0
Minimum value position : 0
Maximum value position : 6


In [42]:
# Matrix

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
print()

print(np.sum(arr,axis = 1)) # Row wise sum
print()

print(np.sum(arr,axis = 0)) # Column wise sum
print()

[[1 2 3]
 [4 5 6]]

[ 6 15]

[5 7 9]

