In [7]:
import numpy as np

marks = np.array([59,23,90,34,67])
print(marks)
print()

print(marks[marks<=50])
print()

print(marks[(marks <= 50) & (marks % 2 == 0)])
print()

print(marks[marks % 2 == 0])
print()

print(marks % 2 == 0)
print()

[59 23 90 34 67]

[23 34]

[34]

[90 34]

[False False  True  True False]



In [8]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix)
print()

even = matrix[matrix % 2 == 0]
print(even)
print()

# Note : Above filter even number from matrix but it always returns flatten matrix

[[1 2 3]
 [4 5 6]]

[2 4 6]



In [9]:
print(np.where(matrix % 2 == 0, matrix, -1))
print()

# Note :  NumPy where function gives same shape with filtering
# Syntax : np.where(filtering condition, performed matrix, filling value)

[[-1  2 -1]
 [ 4 -1  6]]

