In [19]:
import numpy as np

rng = np.random.default_rng()
print(rng.integers(1,31))
print()

print(rng.integers(low=1,high=31,size=5))
print()

print(rng.integers(low=0,high=100,size=(3,3)))
print()

print(np.random.default_rng().integers(1,34,size=(5)))
print()

7

[ 1 22  7 16 11]

[[ 1 61 42]
 [49 92 14]
 [43 22 65]]

[ 5 29 28 29  9]



In [14]:
# If you wnat you to repeat the same random numbers then set seed while initiating with random number

rng = np.random.default_rng(seed=23)
print(rng.integers(1,32,size=(3,3)))
print()

[[ 2 22 14]
 [20  9  4]
 [19  4  4]]



In [15]:
# Floating point numbers generators

print(np.random.uniform(low=-1,high=20))
print()

17.73075979917013



In [33]:
# Shuffle

rng = np.random.default_rng()

names = np.array(["vijay","dheeksha","swathi","diya","shenba"])
rng.shuffle(names)
print(names)
print()

# Choice - Pick only one

print(rng.choice(names))

['dheeksha' 'swathi' 'diya' 'vijay' 'shenba']

shenba
